### ISSUE TITLE
Support for deleting all resource groups in Azure

### ISSUE THREAD

**Issue by istraka** [RedHatQE/cloudwash#75]
### Description
We create new resource group, which name is based version and platform, i.e. _eap-8.0.0.Beta-redhat-20220713-w2k19-openjdk-17-group_, ... which may be different per test run. We follow suggestion that resources in the resource group [share same lifecycle](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal#what-is-a-resource-group) hence once the test run is finished resource group may be deleted. 

### The feature
Sometimes test execution get stuck / fails / ... and test resources may remain up costing us money. It is inconvenient to determine all resource groups that should be cleaned for separate periodical cloudwash run. I would like to have a support for option to delete all resource groups (meeting SLA minutes criteria) except for a list of predefined resource groups (containing monitoring resources, ... )

**Comment by laDok8** [comment]
I would also probably add name matching so it behaves simmilar to [VMs](https://github.com/RedHatQE/cloudwash/blob/2ea2d35b0fede19da31bc347eb54eaa5f5f899f6/conf/azure.yaml.template#L12)

**Comment by istraka** [comment]
We can either introduce a breaking change and make `--all` to delete all resource groups or provide another parameter, i.e. `--all_groups`.

The feature should consider `RESOURCES_SLA_MINUTES` in Azure settings. However `RESOURCE_GROUP` and `REGION` would be irrelevant for the feature.

**Comment by laDok8** [comment]
final template could look like this
```
AZURE:
    AUTH:
        CLIENT_ID:
        SECRET_ID:
        TENANT_ID:
        SUBSCRIPTION_ID:
        # Multiple resource groups can be added like ["foo", "bar"] or ["*"] for all RGs
        RESOURCE_GROUPS: []
        # Multiple regions can be added like ["eu-north", "us-east-2", "us-west"] or ["all"] for all regions
        REGIONS: []
    CRITERIA:
        VM:
            # The VM to be deleted with prepend string, e.g VM name that starts with 'test'
            DELETE_VM: 'test'
            # Number of minutes the deletable VM should be allowed to live, e.g 120 minutes = 2 Hours
            SLA_MINUTES: 120
        DISC:
            UNASSIGNED: True
        NIC:
            UNASSIGNED: True
        PUBLIC_IP:
            UNASSIGNED: True
        RESOURCE_GROUP:
            # Group to be deleted with prepend string, e.g resource group name that starts with 'test'
            DELETE_GROUP: 'test'
            # Delete Resource Group if all resources in resource group crossing SLA minutes
            RESOURCES_SLA_MINUTES:
    EXCEPTIONS:
        VM:
            # VM names that would be skipped from cleanup
            VM_LIST: []
            # VMs that would be stopped from current running state
            STOP_LIST: []
        GROUP:
            # Resource groups that would be skipped from cleanup
            RG_LIST: []
```
